// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXlSIuuiVlSFbLyNasszyWMve2H5sv0s',
    appId: '1:395585238364:web:523519cdd78b491fe27d99',
    messagingSenderId: '395585238364',
    projectId: 'rvspsj',
    authDomain: 'rvspsj.firebaseapp.com',
    databaseURL: 'https://rvspsj-default-rtdb.firebaseio.com',
    storageBucket: 'rvspsj.appspot.com',
    measurementId: 'G-6W8CKVPXDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwcbBLQCyR1FZkeRNgsZZiSGMl19-9jNw',
    appId: '1:395585238364:android:9bbcc4b48eea2a3fe27d99',
    messagingSenderId: '395585238364',
    projectId: 'rvspsj',
    databaseURL: 'https://rvspsj-default-rtdb.firebaseio.com',
    storageBucket: 'rvspsj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyuDhDxIMrg6lg6NeUaBm7Xv0P2R1A2Ew',
    appId: '1:395585238364:ios:120c6eee64a2259be27d99',
    messagingSenderId: '395585238364',
    projectId: 'rvspsj',
    databaseURL: 'https://rvspsj-default-rtdb.firebaseio.com',
    storageBucket: 'rvspsj.appspot.com',
    iosClientId: '395585238364-o8i642k32jl1kuik1difcpd3moiag483.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelmgmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyuDhDxIMrg6lg6NeUaBm7Xv0P2R1A2Ew',
    appId: '1:395585238364:ios:120c6eee64a2259be27d99',
    messagingSenderId: '395585238364',
    projectId: 'rvspsj',
    databaseURL: 'https://rvspsj-default-rtdb.firebaseio.com',
    storageBucket: 'rvspsj.appspot.com',
    iosClientId: '395585238364-o8i642k32jl1kuik1difcpd3moiag483.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelmgmt',
  );
}
